-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 19:03:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LAB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_usuario` (
  `idtipo_usuario` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ctipouser` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(255) NULL,
  `estado_usu` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1,
  `tipo_usuario` TINYINT(3) UNSIGNED NOT NULL,
  `dni_usu` VARCHAR(8) NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipo_usuario1_idx` (`tipo_usuario` ASC) ,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario`)
    REFERENCES `tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_cliente` (
  `idtipo_cliente` INT NOT NULL,
  `ctipo_client` VARCHAR(45) NULL,
  `vigente_cli` TINYINT(1) NULL,
  PRIMARY KEY (`idtipo_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `idcliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_cli` VARCHAR(255) NULL,
  `documento` VARCHAR(12) NULL,
  `telefono_cli` VARCHAR(15) NULL,
  `direccion` VARCHAR(85) NULL,
  `estado_cli` TINYINT(1) NULL,
  `idtipo_cliente` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_tipo_cliente1_idx` (`idtipo_cliente` ASC) ,
  CONSTRAINT `fk_cliente_tipo_cliente1`
    FOREIGN KEY (`idtipo_cliente`)
    REFERENCES `tipo_cliente` (`idtipo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica` (
  `idclinica` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_cli` VARCHAR(100) NULL,
  `telefono_cli` VARCHAR(9) NULL,
  `direccion_cli` VARCHAR(130) NULL,
  `referencia_cli` VARCHAR(70) NULL,
  `estado_cli` BIT(1) NULL DEFAULT 1,
  `ruc_cli` VARCHAR(12) NULL,
  `idcliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idclinica`),
  INDEX `fk_clinica_cliente1_idx` (`idcliente` ASC) ,
  CONSTRAINT `fk_clinica_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `producto` (
  `idproducto` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_pro` VARCHAR(110) NULL,
  `precio_promedio` FLOAT(2) UNSIGNED NULL,
  `estado_pro` TINYINT(3) UNSIGNED NULL DEFAULT 1,
  `cantidad_material` FLOAT(3) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boleta` (
  `idboleta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_crea` DATETIME NOT NULL,
  `precio_total` FLOAT UNSIGNED NULL,
  `estado_pago` BIT(1) NULL DEFAULT 0,
  `estado_entrega` BIT NULL DEFAULT 0,
  `fecha_entrega` DATE NULL,
  `deuda` FLOAT UNSIGNED NOT NULL,
  `idusuario_creador` SMALLINT(6) UNSIGNED NOT NULL,
  `idcliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idboleta`),
  INDEX `fk_voleta_usuario1_idx` (`idusuario_creador` ASC) ,
  INDEX `fk_boleta_cliente1_idx` (`idcliente` ASC) ,
  CONSTRAINT `fk_voleta_usuario1`
    FOREIGN KEY (`idusuario_creador`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleta_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tono_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tono_color` (
  `idtono_color` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ctono` VARCHAR(20) NULL,
  `vigente` BIT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idtono_color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalle_boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalle_boleta` (
  `iddetalle_boleta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` SMALLINT(6) UNSIGNED NULL,
  `sub_total` FLOAT UNSIGNED NULL,
  `descripcion` VARCHAR(200) NULL,
  `precio_unidad` FLOAT UNSIGNED NULL,
  `idproducto` SMALLINT(6) UNSIGNED NOT NULL,
  `idvoleta` INT UNSIGNED NOT NULL,
  `tono_color` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iddetalle_boleta`),
  INDEX `fk_detalle_voleta_producto1_idx` (`idproducto` ASC) ,
  INDEX `fk_detalle_voleta_voleta1_idx` (`idvoleta` ASC) ,
  INDEX `fk_detalle_boleta_tono_color1_idx` (`tono_color` ASC) ,
  CONSTRAINT `fk_detalle_voleta_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_voleta_voleta1`
    FOREIGN KEY (`idvoleta`)
    REFERENCES `boleta` (`idboleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_boleta_tono_color1`
    FOREIGN KEY (`tono_color`)
    REFERENCES `tono_color` (`idtono_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medio_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medio_pago` (
  `idmedio_pago` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cmedio` VARCHAR(60) NULL,
  `est_med` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idmedio_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagos` (
  `idpago` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_pago` DATETIME NULL,
  `cantidad_pago` FLOAT UNSIGNED NOT NULL,
  `idvoleta` INT UNSIGNED NOT NULL,
  `idusuario` SMALLINT(6) UNSIGNED NOT NULL,
  `idmedio_pago` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_modi_adelanto_voleta1_idx` (`idvoleta` ASC) ,
  INDEX `fk_modi_adelanto_usuario1_idx` (`idusuario` ASC) ,
  INDEX `fk_pagos_medio_pago1_idx` (`idmedio_pago` ASC) ,
  CONSTRAINT `fk_modi_adelanto_voleta1`
    FOREIGN KEY (`idvoleta`)
    REFERENCES `boleta` (`idboleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modi_adelanto_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_medio_pago1`
    FOREIGN KEY (`idmedio_pago`)
    REFERENCES `medio_pago` (`idmedio_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontologo` (
  `idodontologo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_odo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `dni_odo` VARCHAR(9) NULL,
  `direccion_odo` VARCHAR(70) NULL,
  `est_odo` BIT(1) NULL DEFAULT 1,
  `ruc_odonto` VARCHAR(11) NULL,
  `idcliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idodontologo`),
  INDEX `fk_odontologo_cliente1_idx` (`idcliente` ASC) ,
  CONSTRAINT `fk_odontologo_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


DELIMITER $$

CREATE DEFINER = CURRENT_USER TRIGGER `LAB3`.`boleta_BEFORE_UPDATE`
BEFORE UPDATE ON `boleta`
FOR EACH ROW
BEGIN
    IF NEW.deuda = 0 THEN
        SET NEW.estado_pago = 1;
    END IF;
END $$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
